### ISSUE TITLE
kas = {git = "https://github.com/kas-gui/kas"} is broken, winit patch is not applied

### ISSUE THREAD

**Issue by m-hugo** [kas-gui/kas#414]
adding master kas to a crate as
```toml
[dependencies]
kas = {git = "https://github.com/kas-gui/kas"}
```
fails because this patch from the root's Cargo.toml isn't applied so the regular winit v0.29.1-beta is used
```toml
[patch.crates-io.winit]
git = "https://github.com/rust-windowing/winit.git"
rev = "cb58c49a90f17734e0405627130674d47c0b8f40"
```

adding manually the patch to my crate's Cargo.toml made it work
